apiVersion: v2
name: t-clo-902
description: A Helm chart to sell cats on Kubernetes
type: application

version: 0.70.0

appVersion: "1.1.0"

dependencies:
   - name: ingress-nginx
     version: 4.7.0
     repository: https://kubernetes.github.io/ingress-nginx
  - name: mysql
    version: 9.10.2
    repository: https://charts.bitnami.com/bitnami
  - name: rabbitmq
    version: 12.0.0
    repository: https://charts.bitnami.com/bitnami
  - name: eck-operator
    version: 2.8.0
    repository: https://helm.elastic.co
  - name: elasticsearch
    version: 0.1.0
    repository: "file://./charts/elasticsearch"
  - name: index
    version: 1.0.1
    repository: "file://./charts/index"
  - name: back
    version: 1.0.0
    repository: "file://./charts/back"
    condition: mysql.enabled
  - name: reporting
    version: 1.0.0
    repository: "file://./charts/reporting"
    condition: mysql.enabled
  - name: front
    version: 1.0.0
    repository: "file://./charts/front"
    condition: back.enabled
  - name: prometheus
    version: 22.6.4
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    version: 6.57.2
    repository: https://grafana.github.io/helm-charts
