apiVersion: v2
name: t-clo-902
description: A Helm chart to sell cats on Kubernetes
type: application

version: 0.69.0

appVersion: "1.1.0"

dependencies:
  - name: mysql
    version: 9.10.2
    repository: https://charts.bitnami.com/bitnami
  - name: index
    version: 1.0.0
    repository: "file://./charts/index"
  - name: back
    version: 1.0.0
    repository: "file://./charts/back"
    condition: mysql.enabled
  - name: reporting
    version: 1.0.0
    repository: "file://./charts/reporting"
    condition: mysql.enabled
  - name: front
    version: 1.0.0
    repository: "file://./charts/front"
    condition: back.enabled
