global:
  imagePullSecret: ghcr-credentials
  ghcr:
    repo: ghcr.io/impsdc/
  elasticsearch:
    elasticsearchPort: "9200"
    elasticsearchScheme: http
    elasticsearchUser: elastic
  amqp:
    user: user
    port: "5672"
  mysql:
    auth:
      database: kubi
      username: kubi
      password: password
      rootPassword: password
      connection: mysql
      port: "3006"
mysql:
  auth:
    createDatabase: true
    database: kubi
    username: kubi
    rootPassword: password
  image:
    debug: true

ingressPaths:
  front:
    path: /
    port: "80"
  back:
    path: /api/
    port: "80"

ghcr:
  imageCredentials:
    registry: ex.io
    username: someone
    password: shhh
    email: someone@host.com

front:
  port: "80"
  image:
    name: kubi-front
    tag: latest

back:
  laravelPort: "80"
  image:
    name: kubi-back
    tag: latest
  configmap:
    appName: Laravel
    appEnv: production
    appKey: base64:h55oToUypq1BJwhcBAbtCnKscJGGS7xXF3zoDNf/yWE=
    appDebug: true
    appUrl: http://kubi.com
    logChannel: stderr
    dbConnection: mysql
    dbPort: "3306"
    dbDatabase: kubi
    broadcastDriver: log
    cacheDriver: file
    queueConnection: sync
    sessionDriver: file
    sessionLifetime: "120"
    rabbitmqPort: "5672"
    rabbitmqVhost: /

index:
  port: "9229"
  image:
    name: kubi-indexer
    tag: latest
  replicaCount: 1

reporting:
  port: "8080"
  image:
    name: kubi-reporting
    tag: latest
  webhook: aea
