dockerConfigJson: YXV0aHM6CiAgICBodHRwczovL2doY3IuaW86CiAgICAgICAgdXNlcm5hbWU6IGJlbmp5aHkKICAgICAgICBwYXNzd29yZDogZ2hwX3dFWlJiWXZ1aFZjZjhiTkwzTmRNWGl0RDk3Wld0UzE5bTBxUwogICAgICAgIGVtYWlsOiByYW1ldC5iZW5qQGdtYWlsLmNvbQogICAgICAgIGF1dGg6IFoyaHdYM2RGV2xKaVdYWjFhRlpqWmpoaVRrd3pUbVJOV0dsMFJEazNXbGQwVXpFNWJUQnhVd28KCg==
imageCredentials:
  registry: ghcr.io/benjyhy/
  username: Benjyhy
  password: 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
  email: ramet.benj@gmail.com
imagePullSecret: ghcr-credentials
elasticsearch:
  elasticsearchHost: "elasticsearch-{{ .Release.Name }}-es-http"
  elasticsearchPort: "9200"
  elasticsearchScheme: http
  elasticsearchUser: elastic
ingressPaths:
  front:
    path: /
    port: "80"
  back:
    path: /api/
    port: "6001"
ghcrRepo: ghcr.io/benjyhy/
amqp:
  user: user
  port: "5672"
mysql:
  imageVersion: 8
  password: saltyproject
  port: "3306"
  dbName: shop
  user: root
front:
  port: "80"
back:
  laravelPort: "6001"
  configmap:
    appName: Laravel
    appEnv: production
    appKey: base64:h55oToUypq1BJwhcBAbtCnKscJGGS7xXF3zoDNf/yWE=
    appDebug: true
    appUrl: http://myshoppp.dev.com
    logChannel: stderr
    dbConnection: mysql
    dbPort: "3306"
    dbDatabase: shop
    broadcastDriver: log
    cacheDriver: file
    queueConnection: sync
    sessionDriver: file
    sessionLifetime: "120"
    rabbitmqPort: "5672"
    rabbitmqVhost: /
    hosts:
      rabbitmqHost: "amqp-{{ .Release.Name }}-rabbitmq"
      dbHost: "{{ .Release.Name }}-mysql-svc"
index:
  replicaCount: 1
  port: "9229"
