apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Release.Name }}-deployment
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
