dockerConfigJson: eyJhdXRocyI6eyJodHRwczovL2doY3IuaW8iOnsidXNlcm5hbWUiOiJiZW5qeWh5IiwicGFzc3dvcmQiOiJnaHBfd0VaUmJZdnVoVmNmOGJOTDNOZE1YaXREOTdaV3RTMTltMHFTIiwiZW1haWwiOiJyYW1ldC5iZW5qQGdtYWlsLmNvbSIsImF1dGgiOiJZbVZ1YW5sb2VUcG5hSEJmZDBWYVVtSlpkblZvVm1ObU9HSk9URE5PWkUxWWFYUkVPVGRhVjNSVE1UbHRNSEZUIn19fQ==
amqp:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 800m
    memory: 1Gi
elasticsearch:
  requests:
    cpu: 5Gi
    memory: 5Gi
  limits:
    cpu: 5Gi
    memory: 1Gi
ingressPaths:
  front:
    path: /
    serviceName: front-service
    port: 80
  back:
    path: /api/
    serviceName: back-service
    port: 6001
global:
  ghcrRepo: ghcr.io/benjyhy/
  elasticsearch:
    elasticsearchHost: elasticsearch-es-http
    elasticsearchPort: "9200"
    elasticsearchScheme: http
    elasticsearchUser: elastic
  amqp:
    user: user
    port: "5672"
  mysql:
    mysqlImageVersion: 8
    mysqlPassword: saltyproject
    mysqlPort: "3306"
    mysqlDbName: shop
    mysqlUser: root
