apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "t-clo-902.nameConfigmap" . }}
data:
{{- range $key, $value := .Values.configmap }}
  {{- if eq $key "hosts" }}
  {{- range $innerKey, $innerValue := .Values.configmap.hosts }}
  {{ $innerKey | snakecase | upper }}: {{ tpl $innerValue . }}
  {{- else }}
  {{ $key | snakecase | upper }}: {{ $value }}
  {{- end }}
{{- end }}
{{- range $key, $value := .Values.global.elasticsearch }}
  {{ $key | snakecase | upper }}: {{ $value }}
{{- end }}