apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-configmap
data:
{{- range $key, $value := .Values }}
  {{ $key | snakecase | upper }}: {{ $value }}
{{- end }}
{{- range $key, $value := .Values.global.elasticsearch }}
  {{ $key | snakecase | upper }}: {{ $value }}
{{- end }}