apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}-{{ .Release.Name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Release.Name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Release.Name }}-deployment
    spec:
      initContainers:
        - name: migrations
          image: {{ .Values.global.ghcrRepo }}{{ .Chart.Name }}:latest
          command:
            - php
          args:
            - artisan
            - migrate
            - --force
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: db_password
            - name: DB_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: back-configmap
                  key: db_connection
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: back-configmap
                  key: db_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: back-configmap
                  key: db_port
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: back-configmap
                  key: db_database
      containers:
        - name: back
          image: {{ .Values.global.ghcrRepo }}{{ .Chart.Name }}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6001
          envFrom:
          - configMapRef:
              name: {{ .Chart.Name }}-{{ .Release.Name }}-configmap
          - secretRef:
              name: env-secrets
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: db_password
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
            - name: ELASTICSEARCH_HOST
              valueFrom:
                configMapKeyRef:
                  name: es-configmap
                  key: es_host
            - name: ELASTICSEARCH_PASS
              valueFrom:
                secretKeyRef:
                  name: es-secret
                  key: es_pass
            - name: ELASTICSEARCH_PORT
              valueFrom:
                configMapKeyRef:
                  name: es-configmap
                  key: es_port
            - name: ELASTICSEARCH_SCHEME
              valueFrom:
                configMapKeyRef:
                  name: es-configmap
                  key: es_scheme
            - name: ELASTICSEARCH_USER
              valueFrom:
                configMapKeyRef:
                  name: es-configmap
                  key: es_user
      {{ include "t-clo-902.imagePullSecret" . }}
