{{- $secretEs := (lookup "v1" "Secret" .Release.Namespace "elasticsearch-es-elastic-user") }}
{{- $secretData := (get $secretEs "data") }}
{{- $esPass := (get $secretData "elastic") }}
apiVersion: v1
kind: Secret
metadata:
  name: { { include "t-clo-902.nameSecret" . } }
stringData:
  DB_USERNAME: { { .Values.mysqlUser } }
  DB_PASSWORD: { { .Values.mysqlPassword } }
  RABBITMQ_USER:
  RABBITMQ_PASSWORD:
  ELASTICSEARCH_PASS: {{ $esPass | quote }}
