{{- $secretEs := (lookup "v1" "Secret" .Release.Namespace "elasticsearch-es-elastic-user") }}
{{- $secretEsData := (get $secretEs "data") }}
{{- $esPass := (get $secretEsData "elastic") }}

{{- $secretAmqp := (lookup "v1" "Secret" .Release.Namespace "amqp-rabbitmq")}}
{{- $secretAmqpData := (get $secretAmqp "data") }}
{{- $amqpPass := (get $secretAmqpData "rabbitmq-password") }}
apiVersion: v1
kind: Secret
metadata:
  name: { { include "t-clo-902.nameSecret" . } }
stringData:
  DB_USERNAME: { { .Values.mysqlUser } }
  DB_PASSWORD: { { .Values.mysqlPassword } }
  RABBITMQ_USER: {{ .Values.global.amqp.user }}
  RABBITMQ_PASSWORD: {{ $amqpPass | quote }}
  ELASTICSEARCH_PASS: {{ $esPass | quote }}
