apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-back-cm
data:
  {{- with .Values.back.configmap.hosts }}
  RABBITMQ_HOST: {{ tpl .rabbitmqHost . | quote }}
  DB_HOST: {{ tpl .dbHost . }}
  {{- end }}
  {{- with .Values.back.configmap }}
  APP_NAME: {{ .appName | quote }}
  APP_ENV: {{ .appEnv | quote }}
  APP_KEY: {{ .appKey | quote }}
  APP_DEBUG: {{ .appDebug | quote }}
  APP_URL: {{ .appUrl | quote }}
  LOG_CHANNEL: {{ .logChannel | quote }}
  DB_CONNECTION: {{ .dbConnection | quote }}
  DB_PORT: {{ .dbPort | quote }}
  DB_DATABASE: {{ .dbDatabase | quote }}
  BROADCAST_DRIVER: {{ .broadcastDriver | quote }}
  CACHE_DRIVER: {{ .cacheDriver | quote }}
  QUEUE_CONNECTION: {{ .queueConnection | quote }}
  SESSION_DRIVER: {{ .sessionDriver | quote }}
  SESSION_LIFETIME: {{ .sessionLifetime | quote }}
  RABBITMQ_PORT: {{ .rabbitmqPort | quote }}
  RABBITMQ_VHOST: {{ .rabbitmqVhost | quote }}
  {{- end }}
  {{- with .Values.elasticsearch }}
  ELASTICSEARCH_HOST: {{ tpl .elasticsearchHost . | quote }}
  ELASTICSEARCH_PORT: {{ .elasticsearchPort | quote }}
  ELASTICSEARCH_SCHEME: {{ .elasticsearchScheme | quote }}
  ELASTICSEARCH_USER: {{ .elasticsearchUser | quote }}
  {{- end }}