apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-back-cm
data:
{{- range $key, $value := .Values.back.configmap }}
  {{- if eq $key "hosts" }}
  {{- range $innerKey, $innerValue := .Values.back.configmap.hosts }}
  {{ $innerKey | snakecase | upper }}: {{ tpl $innerValue . }}
  {{- else }}
  {{ $key | snakecase | upper }}: {{ $value }}
  {{- end }}
{{- end }}
{{- range $key, $value := .Values.elasticsearch }}
  {{ $key | snakecase | upper }}: {{ $value }}
{{- end }}