{{- $secretEs := (lookup "v1" "Secret" .Release.Namespace "elasticsearch-es-elastic-user") }}
{{- $secretEsData := (get $secretEs "data") }}
{{- $esPass := (get $secretEsData "elastic") }}

{{- $secretAmqp := (lookup "v1" "Secret" .Release.Namespace "my-release-rabbitmq")}}
{{- $secretAmqpData := (get $secretAmqp "data") }}
{{- $amqpPass := (get $secretAmqpData "rabbitmq-password") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-back-secret
stringData:
  DB_USERNAME: {{ .Values.mysql.user | quote }}
  DB_PASSWORD: {{ .Values.mysql.password }}
  RABBITMQ_USER: {{ .Values.amqp.user | quote }}
  RABBITMQ_PASSWORD: {{ $amqpPass | quote }}
  ELASTICSEARCH_PASS: {{ $esPass | quote }}
