apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-back-dep
  labels:
    app: {{ .Release.Name }}-back-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-back-dep
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-back-dep
    spec:
      initContainers:
        - name: migrations
          image: {{ .Values.ghcrRepo }}back:latest
          command:
            - php
          args:
            - artisan
            - migrate
            - --force
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-back-cm
          - secretRef:
              name: {{ .Release.Name }}-back-secret
      containers:
        - name: back
          image: {{ .Values.ghcrRepo }}back:latest
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.back.laravelPort }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-back-cm
          - secretRef:
              name: {{ .Release.Name }}-back-secret
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
