{{- $esName := (printf "elasticsearch-%s-es-elastic-user" .Release.Name) }}
{{- $secretEs := (lookup "v1" "Secret" .Release.Namespace (printf "elasticsearch-%s-es-elastic-user" .Release.Name)) }}
{{- $secretEsData := (get $secretEs "data") }}
{{- $esPass := (get $secretEsData "elastic" | b64dec) }}

{{- $amqpName := (printf "amqp-%s-rabbitmq" .Release.Name) }}
{{- $secretAmqp := (lookup "v1" "Secret" .Release.Namespace (printf "amqp-%s-rabbitmq" .Release.Name)) }}
{{- $secretAmqpData := (get $secretAmqp "data") }}
{{- $amqpPass := (get $secretAmqpData "rabbitmq-password" | b64dec) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-back-secret
stringData:
  DB_USERNAME: {{ .Values.mysql.user }}
  DB_PASSWORD: {{ .Values.mysql.password }}
  RABBITMQ_USER: {{ .Values.amqp.user }}
  RABBITMQ_PASSWORD: {{ $amqpPass }}
  ELASTICSEARCH_PASS: {{ $esPass }}
