# {{- $releaseName := (printf .Release.Name) }}
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: {{ .Release.Name }}-cert 
#   namespace: default
# spec:
#   dnsNames:
#     - psdc.tech 
#   secretName: kubi-tls
#   issuerRef:
#     name: {{ .Release.Name }}-letsencrypt-staging
#     kind: ClusterIssuer