{{- define "imagePullSecret.noEnc" }}

{{- $username := (printf .Values.dockerImageCredentials.username) }}
{{- $registry := (printf .Values.dockerImageCredentials.registry) }}
{{- $email := (printf .Values.dockerImageCredentials.email) }}
{{- $password := (printf .Values.dockerImageCredentials.accessToken) }}
{{- $auth := (printf "%s:%s" $username $password  | b64enc) }}

{{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" $registry $username $password $email $auth}}
{{- end }}

{{- define "dockerconfigjson.b64enc" }}
  {{- include "imagePullSecret.noEnc" . | b64enc }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "t-clo-902.dockerCredentials" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "dockerconfigjson.b64enc" . }}