apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 8.7.0
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - name: default
      count: 2
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              {{- range $key, $value := .Values.elasticsearch}}
              {{- with $value }}
              {{ $key }}:
                cpu: {{ .cpu | quote }}
                memory: {{ .limits | quote }}
              {{- end }}
              {{- end }}
            storageClassName: standard