apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-front-svc
spec:
  selector:
    app: {{ .Release.Name }}-front-dep
  type: ClusterIP
  ports:
    - port: {{ .Values.front.port }}
      targetPort: {{ .Values.front.port }}
      protocol: TCP
