apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-front-dep
  labels:
    app: {{ .Release.Name }}-front-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-front-dep
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-front-dep
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.ghcrRepo }}front:latest
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.front.port }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
