{{- $esName := (printf "elasticsearch-%s-es-elastic-user" .Release.Name }}
{{- $secretEs := (lookup "v1" "Secret" .Release.Namespace $esName) }}
{{- $secretEsData := (get $secretEs "data") }}
{{- $esPass := (get $secretEsData "elastic") }}

{{- $amqpName := (printf "amqp-%s-rabbitmq" .Release.Name }}
{{- $secretAmqp := (lookup "v1" "Secret" .Release.Namespace $amqpName) }}
{{- $secretAmqpData := (get $secretAmqp "data") }}
{{- $amqpPass := (get $secretAmqpData "rabbitmq-password") }}

{{- $esHost := (tpl .Values.elasticsearch.elasticsearchHost .) }}
{{- $eckUri := (printf "http://%s:$(esPass)@$(esHost):%s" .Values.elasticsearch.elasticsearchUser .Values.elasticsearch.elasticsearchPort)}}
{{- $amqpUri := (printf "amqp://%s:$(amqpPass)@$(amqpName):%s/"  .Values.amqp.user  .Values.amqp.port) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-index-secret
stringData:
  eck_uri: {{ $eckUri | quote }}
  amqp_uri: {{ $amqpUri | quote }}
