apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-index-dep
  labels:
    app: {{ .Release.Name }}-index-dep
spec:
  replicas: {{ .Values.index.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-index-dep
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-index-dep
    spec:
      containers:
        - name: {{ .Release.Name }}-index-dep
          image: {{ .Values.ghcrRepo }}index:latest
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.index.port }}
          env:
            - name: ELASTICSEARCH_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-index-secret
                  key: eck_uri
            - name: AMQP_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-index-secret
                  key: amqp_uri
      {{ include "t-clo-902.imagePullSecret" . }}
