{{- $esName := (printf "elasticsearch-%s-es-elastic-user" .Release.Name) }}
{{- $secretEs := (lookup "v1" "Secret" .Release.Namespace $esName) }}
{{- $secretEsData := (get $secretEs "data") }}
{{- $esPass := (get $secretEsData "elastic" | b64dec) }}

{{- $amqpName := (printf "amqp-%s-rabbitmq" .Release.Name) }}
{{- $secretAmqp := (lookup "v1" "Secret" .Release.Namespace $amqpName) }}
{{- $secretAmqpData := (get $secretAmqp "data") }}
{{- $amqpPass := (get $secretAmqpData "rabbitmq-password" | b64dec) }}
{{- $trimAmqpPass := (trimSuffix "%" $amqpPass) }}

{{- $esHost := (include "t-clo-902.esHost" .) }}
{{- $eckUri := (printf "http://%s:$(esPass)@$(esHost):%s" .Values.elasticsearch.elasticsearchUser .Values.elasticsearch.elasticsearchPort)}}
{{- $amqpUri := (printf "amqp://%s:$(trimAmqpPass)@$(amqpName):%s/"  .Values.amqp.user  .Values.amqp.port) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-index-secret
stringData:
  eck_uri: {{ $eckUri }}
  amqp_uri: {{ $amqpUri }}
