{{- $secretEs := (lookup "v1" "Secret" .Release.Namespace "elasticsearch-es-elastic-user") }}
{{- $secretEsData := (get $secretEs "data") }}
{{- $esPass := (get $secretEsData "elastic") }}

{{- $secretAmqp := (lookup "v1" "Secret" .Release.Namespace "my-release-rabbitmq")}}
{{- $secretAmqpData := (get $secretAmqp "data") }}
{{- $amqpPass := (get $secretAmqpData "rabbitmq-password") }}

{{- $eckUri := (printf "http://%s:$(esPass)@%s:%s" .Values.elasticsearch.elasticsearchUser .Values.elasticsearch.elasticsearchHost  .Values.elasticsearch.elasticsearchPort)}}
{{- $amqpUri := (printf "amqp://%s:$(amqpPass)@%s-rabbitmq:%s/"  .Values.amqp.user .Release.Name  .Values.amqp.port) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-index-secret
stringData:
  eck_uri: {{ $eckUri | quote }}
  amqp:_uri: {{ $amqpUri | quote }}
