{{- $releaseName := (printf .Release.Name) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: {{ .Release.Name }}-ingress
  namespace: default
spec:
  tls:
    - hosts:
      - psdc.tech  ##NEED A VALID DOMAIN NAME
      secretName: kubi-tls
  rules:
  - http:
      paths:
        {{- range $key, $value := .Values.ingressPaths }}
        {{- with $value }}
        - path: {{ .path }}
          pathType: Prefix
          backend:
            service:
              name: {{ $releaseName }}-{{ .svc }}
              port:
                number: {{ .port }}
        {{- end }}
        {{- end }}
