{{- $releaseName := (printf .Release.Name) }}
apiVersion: cert-manager.io/v1                             
kind: ClusterIssuer                             
metadata:                               
  name: {{ .Release.Name }}-letsencrypt-staging
  annotations:
    kubernetes.io/ingress.class: nginx
spec:                            
  acme:                                 
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: bnzorijana@gmail.com
    privateKeySecretRef:                                                                   
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: bnzorijana@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: nginx