{{- $releaseName := (printf .Release.Name) }}
apiVersion: cert-manager.io/v1                             
kind: ClusterIssuer                             
metadata:                               
  name: {{ .Release.Name }}-letsencrypt-cluster-issuer
  annotations:
    kubernetes.io/ingress.class: nginx
spec:                            
  acme:                                 
    server: https://acme-v02.api.letsencrypt.org/directory
    email: benjy.ramet@yahoo.fr
    privateKeySecretRef:                                                                   
      name: letsencrypt-cluster-issuer-key
    solvers:
    - http01:
        ingress:
          class: nginx