{{- $esName := (printf "elasticsearch-%s-es-elastic-user" .Release.Name) }}
{{- $secretEs := (lookup "v1" "Secret" .Release.Namespace $esName) }}
{{- $secretEsData := (get $secretEs "data") }}
{{- $esPass := (get $secretEsData "elastic" | b64dec) }}

{{- $amqpName := (printf "amqp-%s-rabbitmq" .Release.Name) }}
{{- $secretAmqp := (lookup "v1" "Secret" .Release.Namespace $amqpName) }}
{{- $secretAmqpData := (get $secretAmqp "data") }}
{{- $amqpPass := (get $secretAmqpData "rabbitmq-password" | b64dec) }}

{{- $esHost := (include "t-clo-902.esHost" .) }}
{{- $eckUri := (printf "http://%s:%s@%s:%s" .Values.global.elasticsearch.elasticsearchUser $esPass $esHost .Values.global.elasticsearch.elasticsearchPort)}}
{{- $amqpUri := (printf "amqp://%s:%s@%s:%s/" .Values.global.amqp.user $amqpPass $amqpName .Values.global.amqp.port) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-index-secret
stringData:
  ELASTICSEARCH_URI: {{ $eckUri | quote }}
  AMQP_URI: {{ $amqpUri | quote }}
