{{- $esHost := (include "t-clo-902.esHost" .) }}
{{- $eckUri := (printf "http://%s:%s@%s:%s" .Values.global.elasticsearch.elasticsearchUser .Values.global.elasticsearch.elasticsearchPassword $esHost .Values.global.elasticsearch.elasticsearchPort)}}
{{- $amqpHost := (include "t-clo-902.amqpHost" .) }}
{{- $amqpUri := (printf "amqp://%s:%s@%s:%s/" .Values.global.rabbitmq.auth.username .Values.global.rabbitmq.auth.password $amqpHost .Values.global.rabbitmq.port) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-index-secret
stringData:
  ELASTICSEARCH_URI: {{ $eckUri | quote }}
  AMQP_URI: {{ $amqpUri | quote }}
