{{- $secretEs := (lookup "v1" "Secret" .Release.Namespace "elasticsearch-es-elastic-user") }}
{{- $secretEsData := (get $secretEs "data") }}
{{- $esPass := (get $secretEsData "elastic") }}

{{- $secretAmqp := (lookup "v1" "Secret" .Release.Namespace "amqp-rabbitmq")}}
{{- $secretAmqpData := (get $secretAmqp "data") }}
{{- $amqpPass := (get $secretAmqpData "rabbitmq-password") }}

apiVersion: v1
kind: Secret
metadata:
  name: { { include "nameSecret" . } }
stringData:
  eck_uri: {{ printf "http://%s:$(esPass)@%s:%s" .Values.global.elasticsearch.elasticsearchUser .Values.global.elasticsearch.elasticsearchHost  .Values.global.elasticsearch.elasticsearchPort }}
  amqp:_uri: {{ printf "amqp://%s:$(amqpPass)@%s-rabbitmq:%s/"  .Values.global.amqp.user .Release.Name  .Values.global.amqp.port }}
