apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Release.Name }}
spec:
  version: {{ .Values.elasticsearch.version }}
  nodeSets:
    - name: default
      count: {{ .Values.elasticsearch.nodes }}
      config:
        node.store.allow_mmap: {{ .Values.elasticsearch.mmap }}
