{{- $repo := .Values.global.ghcr.repo }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-back-dep
  labels:
    app: {{ .Release.Name }}-back-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-back-dep
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-back-dep
    spec:
      initContainers:
        - name: migrations
          {{- with .Values.image }}
          image: {{ $repo }}{{ .name }}:{{ .tag }}
          {{- end }}
          command:
            - php
          args:
            - artisan
            - migrate
            - --force
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-back-cm
          - secretRef:
              name: {{ .Release.Name }}-back-secret
      containers:
        - name: back
          {{- with .Values.image }}
          image: {{ $repo }}{{ .name }}:{{ .tag }}
          {{- end }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.laravelPort }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-back-cm
          - secretRef:
              name: {{ .Release.Name }}-back-secret
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecret }}
