apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-back-svc
spec:
  selector:
    app: {{ .Release.Name }}-back-dep
  type: ClusterIP
  ports:
    - port: {{ .Values.laravelPort }}
      targetPort: {{ .Values.laravelPort }}
      protocol: TCP
