{{- $esName := (printf "elasticsearch-%s-es-elastic-user" .Release.Name) }}
{{- $secretEs := (lookup "v1" "Secret" .Release.Namespace $esName) }}
{{- $secretEsData := (get $secretEs "data") }}
{{- $esPass := (get $secretEsData "elastic" | b64dec) }}

{{- $amqpName := (printf "amqp-%s-rabbitmq" .Release.Name) }}
{{- $secretAmqp := (lookup "v1" "Secret" .Release.Namespace $amqpName) }}
{{- $secretAmqpData := (get $secretAmqp "data") }}
{{- $amqpPass := (get $secretAmqpData "rabbitmq-password" | b64dec) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-back-secret
stringData:
  DB_PORT: {{ .Values.global.mysql.port | quote }}
  {{- with .Values.global.mysql.auth }}
  DB_USERNAME: {{ .username | quote }}
  DB_PASSWORD: {{ .password | quote }}
  DB_CONNECTION: {{ .connection | quote }}
  DB_DATABASE: {{ .database | quote }}
  {{- end}}
  RABBITMQ_USER: {{ .Values.global.amqp.user | quote }}
  RABBITMQ_PASSWORD: {{ $amqpPass | quote }}
  ELASTICSEARCH_PASS: {{ $esPass | quote }}
