{{- $esName := (printf "elasticsearch-%s-es-elastic-user" .Release.Name) }}
{{- $secretEs := (lookup "v1" "Secret" .Release.Namespace $esName) }}
{{- $secretEsData := (get $secretEs "data") }}
{{- $esPass := (get $secretEsData "elastic" | b64dec) }}



apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-back-secret
stringData:
  DB_PORT: {{ .Values.global.mysql.port | quote }}
  {{- with .Values.global.mysql.auth }}
  DB_USERNAME: {{ .username | quote }}
  DB_PASSWORD: {{ .password | quote }}
  DB_CONNECTION: {{ .connection | quote }}
  DB_DATABASE: {{ .database | quote }}
  {{- end}}
  RABBITMQ_USER: {{ .Values.global.rabbitmq.auth.username | quote }}
  RABBITMQ_PASSWORD: {{ .Values.global.rabbitmq.auth.password | quote }}
  ELASTICSEARCH_PASS: {{ $esPass | quote }}
