apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-es-secret
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.global.elasticsearch.elasticsearchUser }}
  password: {{ .Values.global.elasticsearch.elasticsearchPassword }}
  roles: superuser