{{- $mysqlHost := (include "t-clo-902.dbHost" .) }}
{{- $mysqlUri := (printf "%s:%s@tcp(%s:%s)/%s" .Values.global.mysql.user .Values.global.mysql.password $mysqlHost .Values.global.mysql.port .Values.global.mysql.dbName) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-reporting-secret
stringData:
  DB_URI: {{ $mysqlUri | quote }}
  WEBHOOK_URL: {{ .Values.webhook | quote }}