apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-reporting-svc
spec:
  selector:
    app: {{ .Release.Name }}-reporting-job
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
