{{- $mysqlHost := (include "t-clo-902.dbHost" .) }}
{{- $mysqlUri := (printf "%s:%s@tcp(%s:%s)/%s" .Values.global.mysql.auth.username .Values.global.mysql.auth.rootPassword $mysqlHost .Values.global.mysql.auth.port .Values.global.mysql.auth.database) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-reporting-secret
stringData:
  DB_URI: {{ $mysqlUri | quote }}
  WEBHOOK_URL: {{ .Values.webhook | quote }}