{{- $repo := .Values.global.ghcr.repo }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-front-dep
  labels:
    app: {{ .Release.Name }}-front-dep
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-front-dep
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-front-dep
    spec:
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.image }}
          image: {{ $repo }}{{ .name }}:{{ .tag }}
          {{- end }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.port }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: {{ include "t-clo-902.dockerCredentials" . }}
